export type Role = 'Admin' | 'Manager' | 'Processor' | 'QA';

export type ProjectStatus = 'Pending' | 'Processing' | 'QA' | 'Complete' | 'On Hold';
export type ProcessType = 'Patent' | 'TM' | 'IDS' | 'Project';

export type Project = {
  id: string;
  applicationNumber: string;
  patentNumber: string;
  refNumber: string;
  from: string;
  subject: string;
  clientName: string;
  process: ProcessType;
  actionTaken: string;
  documentName: string;
  emailDate: string;
  allocationDate: string;
  processor: string;
  qa: string;
  processingDate: string | null;
  qaDate: string | null;
  status: ProjectStatus;
};

export const roles: Role[] = ['Admin', 'Manager', 'Processor', 'QA'];

export const processors = ['Alice', 'Bob', 'Charlie'];
export const qas = ['David', 'Eve', 'Anil', 'Ankit', 'Rahul'];
export const clientNames = ['Client A', 'Client B', 'Client C'];
export const processes: ProcessType[] = ['Patent', 'TM', 'IDS', 'Project'];


export const projects: Project[] = [
  {
    id: '1',
    applicationNumber: 'US16/123,456',
    patentNumber: '10,123,456',
    refNumber: 'REF001',
    from: 'client.a@example.com',
    subject: 'Invention Disclosure - AI in Healthcare',
    clientName: 'Client A',
    process: 'Patent',
    actionTaken: 'First Office Action',
    documentName: 'Response_To_OA.pdf',
    emailDate: '2023-10-01',
    allocationDate: '2023-10-02',
    processor: 'Alice',
    qa: 'David',
    processingDate: '2023-10-05',
    qaDate: '2023-10-07',
    status: 'Complete',
  },
  {
    id: '2',
    applicationNumber: 'US16/234,567',
    patentNumber: '10,234,567',
    refNumber: 'REF002',
    from: 'client.b@example.com',
    subject: 'New Patent Application Filing',
    clientName: 'Client B',
    process: 'Patent',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-10-03',
    allocationDate: '2023-10-04',
    processor: 'Bob',
    qa: 'Anil',
    processingDate: '2023-10-08',
    qaDate: null,
    status: 'QA',
  },
  {
    id: '3',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF003',
    from: 'client.c@example.com',
    subject: 'Follow-up on Application XYZ',
    clientName: 'Client C',
    process: 'TM',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-10-10',
    allocationDate: '2023-10-11',
    processor: 'Alice',
    qa: 'David',
    processingDate: null,
    qaDate: null,
    status: 'Processing',
  },
  {
    id: '4',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF004',
    from: 'client.a@example.com',
    subject: 'Urgent: Client Request',
    clientName: 'Client A',
    process: 'Project',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-10-15',
    allocationDate: '2023-10-16',
    processor: 'Alice',
    qa: 'Eve',
    processingDate: null,
    qaDate: null,
    status: 'Pending',
  },
  {
    id: '5',
    applicationNumber: 'US17/567,890',
    patentNumber: '10,567,890',
    refNumber: 'REF005',
    from: 'client.b@example.com',
    subject: 'Biotech Patent Documents',
    clientName: 'Client B',
    process: 'IDS',
    actionTaken: 'Filed Amendment',
    documentName: 'Amendment.pdf',
    emailDate: '2023-09-20',
    allocationDate: '2023-09-21',
    processor: 'Bob',
    qa: 'Ankit',
    processingDate: '2023-09-25',
    qaDate: '2023-09-28',
    status: 'Complete',
  },
    {
    id: '6',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF006',
    from: 'client.c@example.com',
    subject: 'Query from Patent Office',
    clientName: 'Client C',
    process: 'Patent',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-10-20',
    allocationDate: '2023-10-21',
    processor: 'Charlie',
    qa: 'Rahul',
    processingDate: '2023-10-25',
    qaDate: null,
    status: 'On Hold',
  },
  {
    id: '7',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF007',
    from: 'client.a@example.com',
    subject: 'New Submission for Review',
    clientName: 'Client A',
    process: 'Patent',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-11-01',
    allocationDate: '2023-11-02',
    processor: 'Alice',
    qa: 'David',
    processingDate: null,
    qaDate: null,
    status: 'Processing',
  },
  {
    id: '8',
    applicationNumber: 'US18/111,111',
    patentNumber: '',
    refNumber: 'REF008',
    from: 'client.b@example.com',
    subject: 'Trademark Registration for "Innovate"',
    clientName: 'Client B',
    process: 'TM',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-11-05',
    allocationDate: '2023-11-06',
    processor: 'Bob',
    qa: 'Anil',
    processingDate: null,
    qaDate: null,
    status: 'Pending',
  },
  {
    id: '9',
    applicationNumber: 'US18/222,222',
    patentNumber: '10,987,654',
    refNumber: 'REF009',
    from: 'client.c@example.com',
    subject: 'IDS Filing for Application 222,222',
    clientName: 'Client C',
    process: 'IDS',
    actionTaken: 'Submitted to USPTO',
    documentName: 'IDS_Filing_Confirmation.pdf',
    emailDate: '2023-11-10',
    allocationDate: '2023-11-11',
    processor: 'Charlie',
    qa: 'Ankit',
    processingDate: '2023-11-14',
    qaDate: '2023-11-16',
    status: 'Complete',
  },
  {
    id: '10',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF010',
    from: 'client.a@example.com',
    subject: 'Project Alpha - Phase 1 Deliverables',
    clientName: 'Client A',
    process: 'Project',
    actionTaken: 'Initial draft sent',
    documentName: 'Project_Alpha_Draft.docx',
    emailDate: '2023-11-12',
    allocationDate: '2023-11-13',
    processor: 'Alice',
    qa: 'Eve',
    processingDate: '2023-11-15',
    qaDate: null,
    status: 'QA',
  },
  {
    id: '11',
    applicationNumber: 'US18/333,333',
    patentNumber: '',
    refNumber: 'REF011',
    from: 'client.b@example.com',
    subject: 'Office Action Response Deadline',
    clientName: 'Client B',
    process: 'Patent',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-11-18',
    allocationDate: '2023-11-20',
    processor: 'Bob',
    qa: 'David',
    processingDate: null,
    qaDate: null,
    status: 'Processing',
  },
  {
    id: '12',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF012',
    from: 'client.c@example.com',
    subject: 'New Trademark "LogoMark"',
    clientName: 'Client C',
    process: 'TM',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-11-21',
    allocationDate: '2023-11-22',
    processor: 'Charlie',
    qa: 'Anil',
    processingDate: null,
    qaDate: null,
    status: 'Pending',
  },
  {
    id: '13',
    applicationNumber: 'US18/444,444',
    patentNumber: '',
    refNumber: 'REF013',
    from: 'client.a@example.com',
    subject: 'Invention Disclosure - Quantum Computing',
    clientName: 'Client A',
    process: 'Patent',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-11-25',
    allocationDate: '2023-11-26',
    processor: 'Alice',
    qa: 'Rahul',
    processingDate: null,
    qaDate: null,
    status: 'Processing',
  },
  {
    id: '14',
    applicationNumber: 'US17/111,222',
    patentNumber: '10,888,999',
    refNumber: 'REF014',
    from: 'client.b@example.com',
    subject: 'Final Fee Payment for Patent',
    clientName: 'Client B',
    process: 'Patent',
    actionTaken: 'Fee Paid',
    documentName: 'Fee_Receipt.pdf',
    emailDate: '2023-11-28',
    allocationDate: '2023-11-29',
    processor: 'Bob',
    qa: 'Eve',
    processingDate: '2023-11-30',
    qaDate: '2023-12-01',
    status: 'Complete',
  },
  {
    id: '15',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF015',
    from: 'client.c@example.com',
    subject: 'Project Beta - Status Update',
    clientName: 'Client C',
    process: 'Project',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-12-02',
    allocationDate: '2023-12-03',
    processor: 'Charlie',
    qa: 'Ankit',
    processingDate: null,
    qaDate: null,
    status: 'On Hold',
  },
  {
    id: '16',
    applicationNumber: '',
    patentNumber: '',
    refNumber: 'REF016',
    from: 'client.a@example.com',
    subject: 'IDS Material for Application 123,456',
    clientName: 'Client A',
    process: 'IDS',
    actionTaken: '',
    documentName: '',
    emailDate: '2023-12-05',
    allocationDate: '2023-12-06',
    processor: 'Alice',
    qa: 'David',
    processingDate: null,
    qaDate: null,
    status: 'Pending',
  },
  {
    id: '17',
    applicationNumber: 'US18/555,555',
    patentNumber: '',
    refNumber: 'REF017',
    from: 'client.b@example.com',
    subject: 'Response to Office Action',
    clientName: 'Client B',
    process: 'Patent',
    actionTaken: 'Drafting response',
    documentName: 'Draft_Response.docx',
    emailDate: '2023-12-10',
    allocationDate: '2023-12-11',
    processor: 'Bob',
    qa: 'Anil',
    processingDate: null,
    qaDate: null,
    status: 'Processing',
  },
];
