

export type Role = 'Admin' | 'Manager' | 'Processor' | 'QA' | 'Case Manager';
export const roles: Role[] = ['Admin', 'Manager', 'Processor', 'QA', 'Case Manager'];

export const roleHierarchy: Role[] = ['Admin', 'Manager', 'QA', 'Case Manager', 'Processor'];

export type User = {
    id: string;
    email: string;
    password?: string;
    name: string;
    roles: Role[];
};

export type WorkflowStatus = 'Pending Allocation' | 'With Processor' | 'With QA' | 'Completed';
export const workflowStatuses: WorkflowStatus[] = ['Pending Allocation', 'With Processor', 'With QA', 'Completed'];

export type ProcessorStatus = 'Pending' | 'On Hold' | 'Re-Work' | 'Processed' | 'NTP' | 'Client Query' | 'Already Processed';
export const processorStatuses: ProcessorStatus[] = ['Pending', 'On Hold', 'Re-Work', 'Processed', 'NTP', 'Client Query', 'Already Processed'];
export const processorActionableStatuses: ProcessorStatus[] = ['Pending', 'On Hold', 'Re-Work'];
export const processorSubmissionStatuses: ProcessorStatus[] = ['Processed', 'NTP', 'Client Query', 'Already Processed'];


export type QAStatus = 'Pending' | 'Complete' | 'NTP' | 'Client Query' | 'Already Processed';
export const qaStatuses: QAStatus[] = ['Pending', 'Complete', 'NTP', 'Client Query', 'Already Processed'];
export const qaSubmissionStatuses: QAStatus[] = ['Complete', 'NTP', 'Client Query', 'Already Processed'];

export type ClientStatus = 'Approved' | 'Clarification Required';
export const clientStatuses: ClientStatus[] = ['Approved', 'Clarification Required'];

export type ProcessType = 'Patent' | 'TM' | 'IDS' | 'Project';

export type ProjectEntry = {
    id: string;
    application_number: string | null;
    patent_number: string | null;
    country: string | null;
    status: string | null;
    notes: string | null;
};

export type Project = {
    id: string;
    ref_number: string | null;
    client_name: string;
    process: ProcessType;
    processor: string;
    sender: string | null;
    subject_line: string;
    received_date: string;
    case_manager: string;
    allocation_date: string;
    processing_date: string | null;
    processing_status: ProcessorStatus;
    application_number: string | null;
    patent_number: string | null;
    country: string | null;
    document_type: string | null;
    action_taken: string | null;
    renewal_agent: string | null;
    client_query_description: string | null;
    client_comments: string | null;
    client_error_description: string | null;
    qa: string;
    qa_date: string | null;
    qa_status: QAStatus;
    qa_remark: string | null;
    error: string | null;
    rework_reason: string | null;
    email_renaming: string | null;
    email_forwarded: string | null;
    reportout_date: string | null;
    manager_name: string | null;
    clientquery_status: ClientStatus | null;
    workflowStatus: WorkflowStatus; // This will be derived or managed alongside statuses
    entries?: ProjectEntry[];
};


export const processors = ['Alice', 'Bob', 'Charlie', 'Rahul'];
export const qas = ['David', 'Eve', 'Anil', 'Ankit', 'Rahul', 'Bob', 'Manager User'];
export const clientNames = ['Client A', 'Client B', 'Client C'];
export const processes: ProcessType[] = ['Patent', 'TM', 'IDS', 'Project'];
export const projectStatuses: any[] = ["Pending", "Completed", "On Hold"];
export const countries = ['USA', 'India', 'Canada', 'UK', 'Germany'];
export const caseManagers = ['CM Alice', 'CM Bob'];


export let users: Omit<User, 'id'>[] = [
    { email: 'admin@example.com', password: 'password', name: 'Admin User', roles: ['Admin', 'Manager'] },
    { email: 'manager@example.com', password: 'password', name: 'Manager User', roles: ['Manager', 'QA'] },
    { email: 'alice@example.com', password: 'password', name: 'Alice', roles: ['Processor'] },
    { email: 'bob@example.com', password: 'password', name: 'Bob', roles: ['Processor', 'QA'] },
    { email: 'charlie@example.com', password: 'password', name: 'Charlie', roles: ['Processor'] },
    { email: 'david@example.com', password: 'password', name: 'David', roles: ['QA'] },
    { email: 'eve@example.com', password: 'password', name: 'Eve', roles: ['QA'] },
    { email: 'anil@example.com', password: 'password', name: 'Anil', roles: ['QA'] },
    { email: 'ankit@example.com', password: 'password', name: 'Ankit', roles: ['QA'] },
    { email: 'rahul@example.com', password: 'password', name: 'Rahul', roles: ['Admin', 'Manager', 'QA', 'Processor'] },
    { email: 'cm.alice@example.com', password: 'password', name: 'CM Alice', roles: ['Case Manager'] },
    { email: 'cm.bob@example.com', password: 'password', name: 'CM Bob', roles: ['Case Manager'] },
];

let initialProjects: Omit<Project, 'id'>[] = [
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'Patent',
    application_number: 'US16/123,456',
    patent_number: '10,123,456',
    received_date: '2023-10-01',
    allocation_date: '2023-10-02',
    processor: 'Rahul',
    qa: 'Rahul',
    case_manager: 'CM Alice',
    workflowStatus: 'Completed',
    processing_status: 'Processed',
    qa_status: 'Complete',
    processing_date: '2023-10-05',
    qa_date: '2023-10-07',
    rework_reason: null,
    subject_line: 'Invention Disclosure - AI in Healthcare',
    client_comments: null,
    clientquery_status: null,
    entries: [
        { id: 'entry1', application_number: 'US16/123,456', patent_number: '10,123,456', country: 'USA', status: 'Filed', notes: 'Initial notes' }
    ],
    sender: 'client@clienta.com',
    country: 'USA',
    document_type: 'Disclosure',
    action_taken: 'Filed',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: 'Looks good.',
    error: null,
    email_renaming: 'REF001_Disclosure.eml',
    email_forwarded: 'attorney@lawfirm.com',
    reportout_date: '2023-10-08',
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'Patent',
    application_number: 'US16/234,567',
    patent_number: '10,234,567',
    received_date: '2023-10-03',
    allocation_date: '2023-10-04',
    processor: 'Rahul',
    qa: 'Rahul',
    case_manager: 'CM Bob',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Pending',
    processing_date: '2023-10-08',
    qa_date: null,
    rework_reason: null,
    subject_line: 'New Patent Application Filing',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'contact@clientb.com',
    country: 'USA',
    document_type: 'Application',
    action_taken: 'Pending Filing',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF002_NewApp.eml',
    email_forwarded: 'attorney@lawfirm.com',
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'TM',
    application_number: null,
    patent_number: null,
    received_date: '2023-10-10',
    allocation_date: '2023-10-11',
    processor: 'Rahul',
    qa: 'Rahul',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'Follow-up on Application XYZ',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'legal@clientc.com',
    country: 'Canada',
    document_type: 'Correspondence',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'IDS',
    application_number: 'US16/123,456',
    patent_number: null,
    received_date: '2023-10-15',
    allocation_date: '2023-10-16',
    processor: 'Alice',
    qa: 'David',
    case_manager: 'CM Bob',
    workflowStatus: 'With Processor',
    processing_status: 'Re-Work',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: 'Incorrect citations used.',
    subject_line: 'Information Disclosure Statement for App 123',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'client@clienta.com',
    country: 'USA',
    document_type: 'IDS Form',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'Patent',
    application_number: null,
    patent_number: null,
    received_date: '2023-10-18',
    allocation_date: '2023-10-19',
    processor: 'Rahul',
    qa: 'Rahul',
    case_manager: 'CM Alice',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Client Query',
    processing_date: '2023-10-22',
    qa_date: null,
    rework_reason: 'Need clarification on figure 3.',
    subject_line: 'Response to office action',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'contact@clientb.com',
    country: 'USA',
    document_type: 'Office Action Response',
    action_taken: 'Submitted to USPTO',
    renewal_agent: null,
    client_query_description: 'Client needs to confirm if Figure 3A or 3B is the correct one to use.',
    client_error_description: null,
    qa_remark: 'Sent to case manager for client clarification.',
    error: null,
    email_renaming: 'REF005_OA_Response.eml',
    email_forwarded: 'attorney@lawfirm.com',
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'Project',
    application_number: null,
    patent_number: null,
    received_date: '2024-01-20',
    allocation_date: '2024-01-21',
    processor: 'Alice',
    qa: 'Eve',
    case_manager: 'CM Bob',
    workflowStatus: 'Completed',
    processing_status: 'Processed',
    qa_status: 'Complete',
    processing_date: '2024-01-25',
    qa_date: '2024-01-26',
    rework_reason: null,
    subject_line: 'Q1 Portfolio Review',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'manager@clientc.com',
    country: 'UK',
    document_type: 'Report',
    action_taken: 'Sent to client',
    renewal_agent: 'Renewals Inc.',
    client_query_description: null,
    client_error_description: null,
    qa_remark: 'All clear.',
    error: null,
    email_renaming: 'REF006_Q1_Review.eml',
    email_forwarded: null,
    reportout_date: '2024-01-27',
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'Patent',
    application_number: 'EP3456789',
    patent_number: null,
    received_date: '2024-02-10',
    allocation_date: '2024-02-11',
    processor: 'Bob',
    qa: 'Anil',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'On Hold',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'European Patent Validation',
    client_comments: 'Awaiting instructions from European counsel.',
    clientquery_status: null,
    entries: [],
    sender: 'paralegal@clienta.com',
    country: 'Germany',
    document_type: 'Validation Request',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'TM',
    application_number: 'UK000012345',
    patent_number: null,
    received_date: '2024-03-01',
    allocation_date: '2024-03-02',
    processor: 'Charlie',
    qa: 'David',
    case_manager: 'CM Bob',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'Trademark renewal for "Innovate" logo',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'branding@clientb.com',
    country: 'UK',
    document_type: 'Renewal Reminder',
    action_taken: null,
    renewal_agent: 'UK Agents Ltd',
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'Patent',
    application_number: 'IN202312345',
    patent_number: null,
    received_date: '2024-03-15',
    allocation_date: '2024-03-16',
    processor: 'Alice',
    qa: 'Ankit',
    case_manager: 'CM Alice',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Pending',
    processing_date: '2024-03-20',
    qa_date: null,
    rework_reason: null,
    subject_line: 'Filing receipt for Indian patent application',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'ipcounsel@clientc.com',
    country: 'India',
    document_type: 'Filing Receipt',
    action_taken: 'Docketed',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF009_IN_Receipt.eml',
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'IDS',
    application_number: 'US16/987,654',
    patent_number: null,
    received_date: '2024-04-01',
    allocation_date: '2024-04-02',
    processor: 'Bob',
    qa: 'Eve',
    case_manager: 'CM Bob',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'New prior art for AI project',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'inventor@clienta.com',
    country: 'USA',
    document_type: 'Prior Art',
    action_taken: 'Prepare IDS',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'Patent',
    application_number: 'CA2987654',
    patent_number: null,
    received_date: '2024-04-05',
    allocation_date: '2024-04-05',
    processor: 'Charlie',
    qa: 'David',
    case_manager: 'CM Alice',
    workflowStatus: 'Completed',
    processing_status: 'Processed',
    qa_status: 'Complete',
    processing_date: '2024-04-10',
    qa_date: '2024-04-11',
    rework_reason: null,
    subject_line: 'Canadian Office Action',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'foreignfiling@clientb.com',
    country: 'Canada',
    document_type: 'Office Action',
    action_taken: 'Reviewed',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: 'No issues found.',
    error: null,
    email_renaming: 'REF011_CA_OA.eml',
    email_forwarded: null,
    reportout_date: '2024-04-12',
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'Project',
    application_number: null,
    patent_number: null,
    received_date: '2024-04-15',
    allocation_date: '2024-04-16',
    processor: 'Alice',
    qa: 'Anil',
    case_manager: 'CM Bob',
    workflowStatus: 'With Processor',
    processing_status: 'Client Query',
    qa_status: 'Pending',
    processing_date: '2024-04-18',
    qa_date: null,
    rework_reason: null,
    subject_line: 'Budget planning for 2025',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'finance@clientc.com',
    country: null,
    document_type: 'Financials',
    action_taken: null,
    renewal_agent: null,
    client_query_description: 'Need breakdown of costs per region.',
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF012_Budget.eml',
    email_forwarded: 'manager@example.com',
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'TM',
    application_number: null,
    patent_number: null,
    received_date: '2024-04-20',
    allocation_date: '2024-04-21',
    processor: 'Bob',
    qa: 'Ankit',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'New logo search',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'marketing@clienta.com',
    country: 'USA',
    document_type: 'Search Request',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'IDS',
    application_number: 'US16/234,567',
    patent_number: null,
    received_date: '2024-05-01',
    allocation_date: '2024-05-02',
    processor: 'Charlie',
    qa: 'Eve',
    case_manager: 'CM Bob',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Pending',
    processing_date: '2024-05-05',
    qa_date: null,
    rework_reason: null,
    subject_line: 'Supplemental IDS',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'paralegal@clientb.com',
    country: 'USA',
    document_type: 'IDS Form',
    action_taken: 'To be filed',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF014_IDS.eml',
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'Patent',
    application_number: 'IN202312345',
    patent_number: '43210',
    received_date: '2024-05-10',
    allocation_date: '2024-05-11',
    processor: 'Alice',
    qa: 'David',
    case_manager: 'CM Alice',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Client Query',
    processing_date: '2024-05-15',
    qa_date: '2024-05-16',
    rework_reason: null,
    subject_line: 'Patent Granted in India!',
    client_comments: 'Please proceed with fee payment.',
    clientquery_status: 'Approved',
    entries: [],
    sender: 'ipcounsel@clientc.com',
    country: 'India',
    document_type: 'Grant Notification',
    action_taken: 'Docketed Grant',
    renewal_agent: 'Indian Renewals Co',
    client_query_description: 'Grant fee payment confirmation needed.',
    client_error_description: null,
    qa_remark: 'Forwarded to client for approval to pay fees.',
    error: null,
    email_renaming: 'REF015_IN_Grant.eml',
    email_forwarded: 'billing@example.com',
    reportout_date: '2024-05-17',
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'Patent',
    application_number: 'US17/111,111',
    patent_number: null,
    received_date: '2024-05-12',
    allocation_date: '2024-05-13',
    processor: 'Rahul',
    qa: 'Anil',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'New Wearable Tech Disclosure',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'rnd@clienta.com',
    country: 'USA',
    document_type: 'Disclosure',
    action_taken: 'Reviewing',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,

    reportout_date: null,
    manager_name: 'Manager User',
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'TM',
    application_number: null,
    patent_number: null,
    received_date: '2024-05-14',
    allocation_date: '2024-05-15',
    processor: 'Bob',
    qa: 'Eve',
    case_manager: 'CM Bob',
    workflowStatus: 'Completed',
    processing_status: 'Processed',
    qa_status: 'Complete',
    processing_date: '2024-05-18',
    qa_date: '2024-05-19',
    rework_reason: null,
    subject_line: 'Cease and Desist letter draft',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'legal@clientc.com',
    country: 'USA',
    document_type: 'Legal Draft',
    action_taken: 'Sent to client for approval',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: 'Draft looks solid.',
    error: null,
    email_renaming: 'REF017_CD_Draft.eml',
    email_forwarded: 'seniorcounsel@clientc.com',
    reportout_date: '2024-05-20',
    manager_name: 'Manager User',
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'Project',
    application_number: null,
    patent_number: null,
    received_date: '2024-05-16',
    allocation_date: '2024-05-17',
    processor: 'Alice',
    qa: 'Ankit',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'On Hold',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'IP Due Diligence for M&A',
    client_comments: 'Awaiting target company data room access.',
    clientquery_status: null,
    entries: [],
    sender: 'corpdev@clientb.com',
    country: null,
    document_type: 'M&A Request',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User',
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'Patent',
    application_number: 'PCT/US2024/12345',
    patent_number: null,
    received_date: '2024-05-18',
    allocation_date: '2024-05-20',
    processor: 'Charlie',
    qa: 'David',
    case_manager: 'CM Bob',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Pending',
    processing_date: '2024-05-22',
    qa_date: null,
    rework_reason: null,
    subject_line: 'PCT Filing and Search Report',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'client@clienta.com',
    country: 'International',
    document_type: 'PCT Filing',
    action_taken: 'Docketed Search Report deadline.',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF019_PCT_Filing.eml',
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User',
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'IDS',
    application_number: 'IN202312345',
    patent_number: null,
    received_date: '2024-05-21',
    allocation_date: '2024-05-22',
    processor: 'Bob',
    qa: 'Rahul',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'New references for Indian application',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'ipcounsel@clientc.com',
    country: 'India',
    document_type: 'Prior Art',
    action_taken: 'To prepare IDS',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User',
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'Patent',
    application_number: 'US18/000,001',
    patent_number: null,
    received_date: '2024-06-01',
    allocation_date: '2024-06-02',
    processor: 'Alice',
    qa: 'David',
    case_manager: 'CM Alice',
    workflowStatus: 'With Processor',
    processing_status: 'Pending',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: null,
    subject_line: 'Project Dragonfly - New Invention',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'rndlead@clienta.com',
    country: 'USA',
    document_type: 'Invention Disclosure',
    action_taken: 'Docketing',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,

    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'TM',
    application_number: 'EU018111222',
    patent_number: null,
    received_date: '2024-06-03',
    allocation_date: '2024-06-04',
    processor: 'Bob',
    qa: 'Eve',
    case_manager: 'CM Bob',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Pending',
    processing_date: '2024-06-07',
    qa_date: null,
    rework_reason: null,
    subject_line: 'EU Trademark Opposition',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'eucounsel@clientb.com',
    country: 'EU',
    document_type: 'Opposition Notice',
    action_taken: 'Reviewing',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: 'REF022_EU_Opposition.eml',
    email_forwarded: 'litigation@example.com',
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client C',
    process: 'Patent',
    application_number: 'JP2024-001234',
    patent_number: null,
    received_date: '2024-06-05',
    allocation_date: '2024-06-06',
    processor: 'Charlie',
    qa: 'Anil',
    case_manager: 'CM Alice',
    workflowStatus: 'Completed',
    processing_status: 'Processed',
    qa_status: 'Complete',
    processing_date: '2024-06-10',
    qa_date: '2024-06-11',
    rework_reason: null,
    subject_line: 'Japanese Office Action Response Filed',
    client_comments: 'Thank you for the quick turnaround.',
    clientquery_status: 'Approved',
    entries: [],
    sender: 'jp_agent@clientc.com',
    country: 'Japan',
    document_type: 'Filing Confirmation',
    action_taken: 'Noted',
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: 'Good work.',
    error: null,
    email_renaming: 'REF023_JP_Response.eml',
    email_forwarded: null,
    reportout_date: '2024-06-12',
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client A',
    process: 'IDS',
    application_number: 'US17/111,111',
    patent_number: null,
    received_date: '2024-06-08',
    allocation_date: '2024-06-09',
    processor: 'Alice',
    qa: 'Ankit',
    case_manager: 'CM Bob',
    workflowStatus: 'With Processor',
    processing_status: 'Re-Work',
    qa_status: 'Pending',
    processing_date: null,
    qa_date: null,
    rework_reason: 'Missed a key reference from the list.',
    subject_line: 'URGENT: Supplemental IDS for Wearable Tech',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'paralegal@clienta.com',
    country: 'USA',
    document_type: 'IDS Form',
    action_taken: null,
    renewal_agent: null,
    client_query_description: null,
    client_error_description: null,
    qa_remark: null,
    error: null,
    email_renaming: null,
    email_forwarded: null,
    reportout_date: null,
    manager_name: 'Manager User'
  },
  {
    ref_number: '',
    client_name: 'Client B',
    process: 'Patent',
    application_number: 'CA2987654',
    patent_number: null,
    received_date: '2024-06-11',
    allocation_date: '2024-06-12',
    processor: 'Bob',
    qa: 'Rahul',
    case_manager: 'CM Alice',
    workflowStatus: 'With QA',
    processing_status: 'Processed',
    qa_status: 'Client Query',
    processing_date: '2024-06-15',
    qa_date: null,
    rework_reason: null,
    subject_line: 'Client Query on Canadian OA Response',
    client_comments: null,
    clientquery_status: null,
    entries: [],
    sender: 'foreignfiling@clientb.com',
    country: 'Canada',
    document_type: 'Client Email',
    action_taken: 'Awaiting client response',
    renewal_agent: null,
    client_query_description: 'Client is asking about the potential cost implications of the proposed amendment.',
    client_error_description: null,
    qa_remark: 'Forwarded to Case Manager for client communication.',
    error: null,
    email_renaming: 'REF025_CA_Query.eml',
    email_forwarded: 'cm.alice@example.com',
    reportout_date: null,
    manager_name: 'Manager User'
  },
];


export let projects: Project[] = initialProjects.map((p, index) => ({
  ...p,
  id: `PF${String(index + 1).padStart(6, '0')}`,
}));

    